# https://school.programmers.co.kr/learn/courses/30/lessons/133025
/*
FIRST_HALF
    SHIPMENT_ID	INT(N)	FALSE
    FLAVOR	VARCHAR(N)	FALSE
    TOTAL_ORDER	INT(N)	FALSE
ICECREAM_INFO
    FLAVOR	VARCHAR(N)	FALSE
    INGREDIENT_TYPE	VARCHAR(N)	FALSE
*/


SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
         JOIN ICECREAM_INFO AS II
              ON FH.FLAVOR = II.FLAVOR
WHERE FH.TOTAL_ORDER > 3000
  AND II.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FH.TOTAL_ORDER DESC;


/*
SELECT
Lv.1. 현 시점 완료한 사람 40,174명, 정답률 85%
*/
