# https://school.programmers.co.kr/learn/courses/30/lessons/151139
/*
CAR_RENTAL_COMPANY_RENTAL_HISTORY
    HISTORY_ID	INTEGER	FALSE
    CAR_ID	INTEGER	FALSE
    START_DATE	DATE	FALSE
    END_DATE	DATE	FALSE
*/


-- 코드를 입력하세요
WITH ELIGIBLE_CARS AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
      AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT MONTH(START_DATE) AS MONTH,
       CAR_ID,
       COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    AND CAR_ID IN (SELECT CAR_ID FROM ELIGIBLE_CARS)
GROUP BY MONTH, CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH ASC, CAR_ID DESC;


/*
GROUP BY
Lv.3. 현 시점 완료한 사람 14,744명, 정답률 73%
*/
