# https://school.programmers.co.kr/learn/courses/30/lessons/131118
/*
REST_INFO
    REST_ID	VARCHAR(5)	FALSE
    REST_NAME	VARCHAR(50)	FALSE
    FOOD_TYPE	VARCHAR(20)	TRUE
    VIEWS	NUMBER	TRUE
    FAVORITES	NUMBER	TRUE
    PARKING_LOT	VARCHAR(1)	TRUE
    ADDRESS	VARCHAR(100)	TRUE
    TEL	VARCHAR(100)	TRUE
REST_REVIEW
    REVIEW_ID	VARCHAR(10)	FALSE
    REST_ID	VARCHAR(10)	TRUE
    MEMBER_ID	VARCHAR(100)	TRUE
    REVIEW_SCORE	NUMBER	TRUE
    REVIEW_TEXT	VARCHAR(1000)	TRUE
    REVIEW_DATE	DATE	TRUE
*/


-- 코드를 입력하세요
SELECT RI.REST_ID,
       RI.REST_NAME,
       RI.FOOD_TYPE,
       RI.FAVORITES,
       RI.ADDRESS,
       ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS RI
         INNER JOIN REST_REVIEW AS RR
                    ON RI.REST_ID = RR.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC;


/*
SELECT
Lv.4. 현 시점 완료한 사람 23,268명, 정답률 75%
*/
